In [2]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
# plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 결측치 시각화를 위한 라이브러리
import missingno

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

### 데이터를 불러와 합친다

In [9]:
df1 = pd.read_parquet('open/test/6.채널정보/201807_test_채널정보.parquet')
df2 = pd.read_parquet('open/test/6.채널정보/201808_test_채널정보.parquet')
df3 = pd.read_parquet('open/test/6.채널정보/201809_test_채널정보.parquet')
df4 = pd.read_parquet('open/test/6.채널정보/201810_test_채널정보.parquet')
df5 = pd.read_parquet('open/test/6.채널정보/201811_test_채널정보.parquet')
df6 = pd.read_parquet('open/test/6.채널정보/201812_test_채널정보.parquet')

In [13]:
df7 = pd.concat([df1, df2, df3, df4, df5, df6], axis=0, ignore_index=True)

In [15]:
df7

,기준년월,ID,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,인입일수_ARS_R6M,인입월수_ARS_R6M,인입후경과월_ARS,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,...,당사PAY_방문횟수_R6M,당사PAY_방문월수_R6M,당사멤버쉽_방문횟수_B0M,당사멤버쉽_방문횟수_R6M,당사멤버쉽_방문월수_R6M,OS구분코드,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M
0,201807,TEST_00000,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,IOS,0,0,0,0
1,201807,TEST_00001,1회 이상,1회 이상,1,1,5,0,0,0,...,0,0,0,0,0,Android,0,0,0,0
2,201807,TEST_00002,1회 이상,1회 이상,1,1,3,0,0,0,...,0,0,0,2,1,Android,0,0,0,0
3,201807,TEST_00003,1회 이상,1회 이상,2,1,3,0,0,0,...,0,0,0,0,0,None,0,0,0,0
4,201807,TEST_00004,1회 이상,1회 이상,1,1,1,0,0,0,...,0,0,0,0,0,None,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
599996,201812,TEST_99996,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,3,7,3,3
599997,201812,TEST_99997,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
599998,201812,TEST_99998,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,Android,7,22,4,12
599999,201812,TEST_99999,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0

### 컬럼을 선택한다

In [19]:
cols_to_save = ['기준년월',
                'ID',
                '인입일수_ARS_R6M',
                '인입횟수_ARS_B0M', 
                '이용메뉴건수_ARS_B0M', 
                '인입일수_ARS_B0M', 
                '방문일수_앱_R6M', 
                '방문횟수_PC_B0M', 
                '방문일수_PC_B0M', 
                '방문횟수_앱_B0M', 
                '방문일수_앱_B0M', 
                '인입횟수_IB_R6M', 
                '인입일수_IB_R6M', 
                '이용메뉴건수_IB_R6M', 
                '상담건수_R6M', 
                'IB문의건수_사용승인내역_R6M', 
                'IB문의건수_선결제_R6M', 
                '불만제기후경과월_R12M', 
                '홈페이지_금융건수_R6M', 
                '홈페이지_선결제건수_R6M', 
                '홈페이지_금융건수_R3M', 
                '홈페이지_선결제건수_R3M', 
                '인입횟수_ARS_R6M', 
                '이용메뉴건수_ARS_R6M', 
                '방문횟수_PC_R6M', 
                '방문일수_PC_R6M', 
                '방문횟수_앱_R6M']

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [23]:
df8 = df7[cols_to_save].copy()

In [25]:
df8

,기준년월,ID,인입일수_ARS_R6M,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,방문일수_앱_R6M,방문횟수_PC_B0M,방문일수_PC_B0M,방문횟수_앱_B0M,...,불만제기후경과월_R12M,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,방문횟수_앱_R6M
0,201807,TEST_00000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,1,0,0,0,3,0,0,3,...,12,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,1,0,0,0,0,0,0,0,...,12,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,2,0,0,0,0,0,0,0,...,12,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,1,0,0,0,0,0,0,0,...,12,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,201812,TEST_99996,0,0,0,0,16,0,0,3,...,12,3,7,3,3,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599997,201812,TEST_99997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,201812,TEST_99998,0,0,0,0,37,0,0,9,...,12,7,22,4,12,1회 이상,1회 이상,1회 이상,1회 이상,40회 이상
599999,201812,TEST_99999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [31]:
import re
import pandas as pd

# ────────────────────────────────────────────
# 1) 서열(순서) 컬럼 목록
# ────────────────────────────────────────────
ord_cols = [
    '인입횟수_ARS_R6M',
    '이용메뉴건수_ARS_R6M',
    '방문횟수_PC_R6M',
    '방문일수_PC_R6M',
    '방문횟수_앱_R6M'
]

# ────────────────────────────────────────────
# 2) 인코딩 함수  ―  df[col]을 숫자로 **덮어쓰기**
# ────────────────────────────────────────────
def ordinal_encode_inplace(df: pd.DataFrame, col: str):
    """
    '1회 이상', '10회 이상' → 0,1,2… 로 변환
    숫자가 없는 값은 -1
    """
    # (1) 고유 카테고리 추출
    uniques = df8[col].dropna().unique()

    # (2) '숫자' 추출  → 정렬 키
    def extract_num(s):
        m = re.search(r'\d+', str(s))
        return int(m.group()) if m else float('inf')   # 숫자 없으면 inf
    
    ordered = sorted(uniques, key=extract_num)

    # (3) 매핑 딕셔너리 생성
    mapping = {cat: idx for idx, cat in enumerate(ordered) if extract_num(cat) != float('inf')}
    mapping.update({cat: -1 for cat in ordered if extract_num(cat) == float('inf')})

    # (4) 실제 덮어쓰기
    df8[col] = df8[col].map(mapping).astype('int8')

    print(f"[{col}] 매핑 ▶ {mapping}")

# ────────────────────────────────────────────
# 3) 모든 서열 컬럼 인코딩
# ────────────────────────────────────────────
for c in ord_cols:
    ordinal_encode_inplace(df8, c)

# ────────────────────────────────────────────
# 4) 확인
# ────────────────────────────────────────────
print(df8[ord_cols].head())
print(df8[ord_cols].dtypes)   # int8 로 변경된 것 확인

[인입횟수_ARS_R6M] 매핑 ▶ {0: 0, 1: 1}
[이용메뉴건수_ARS_R6M] 매핑 ▶ {0: 0, 1: 1, 2: 2, 3: 3}
[방문횟수_PC_R6M] 매핑 ▶ {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
[방문일수_PC_R6M] 매핑 ▶ {0: 0, 1: 1, 2: 2, 3: 3}
[방문횟수_앱_R6M] 매핑 ▶ {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}
   인입횟수_ARS_R6M  이용메뉴건수_ARS_R6M  방문횟수_PC_R6M  방문일수_PC_R6M  방문횟수_앱_R6M
0             0               0            0            0           0
1             0               0            0            0           0
2             0               0            0            0           0
3             0               0            0            0           0
4             0               0            0            0           0
인입횟수_ARS_R6M      int8
이용메뉴건수_ARS_R6M    int8
방문횟수_PC_R6M       int8
방문일수_PC_R6M       int8
방문횟수_앱_R6M        int8
dtype: object

In [33]:
df8

,기준년월,ID,인입일수_ARS_R6M,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,방문일수_앱_R6M,방문횟수_PC_B0M,방문일수_PC_B0M,방문횟수_앱_B0M,...,불만제기후경과월_R12M,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,방문횟수_앱_R6M
0,201807,TEST_00000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,201807,TEST_00001,1,0,0,0,3,0,0,3,...,12,0,0,0,0,0,0,0,0,0
2,201807,TEST_00002,1,0,0,0,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
3,201807,TEST_00003,2,0,0,0,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
4,201807,TEST_00004,1,0,0,0,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599996,201812,TEST_99996,0,0,0,0,16,0,0,3,...,12,3,7,3,3,0,0,0,0,1
599997,201812,TEST_99997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599998,201812,TEST_99998,0,0,0,0,37,0,0,9,...,12,7,22,4,12,0,0,0,0,4
599999,201812,TEST_99999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df8.to_parquet('open/test/6.채널정보/test_채널정보_parquet')